Pretrain:
  n_clusters: 30
  batch_size: 256
  n_epochs: 200
  in_dim: 46
  edge_dim: 10
  hidden_dim: 256
  evaluate_step: 50
  t1: 1
  t2: 1
  lr: 0.0005
  l2: 0.0001
  alpha: 1
  phi: 1
  theta: 1
  yeta: 1
  gamma: 0.999
  seed: 2023
  dataset: bace
  test_name: bace_proto
  task_type: classification

Train:
  n_tasks: 1
  batch_size: 256
  n_epochs: 200
  valid_step: 5
  lr: 0.001
  h1: 1
  h2: 0.1
  l2: 0.0001
  predict: fuse
  seed: 2023
  dataset: bace
  test_name: predict_bace_proto
  pre_test_name: bace_proto
#  pre_test_name: hiv_proto_test
  metric: rocauc
  task_type: classification
